version: '3'
services:
  opencti-dev-redis:
    container_name: opencti-dev-redis
    image: redis:6.2.1
    restart: always
    ports:
      - 6379:6379
  opencti-dev-elasticsearch:
    container_name: opencti-dev-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
  opencti-dev-minio:
    container_name: opencti-dev-minio
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: yoshida
      MINIO_SECRET_KEY: torajiro
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  opencti-dev-rabbitmq:
    container_name: opencti-dev-rabbitmq
    image: rabbitmq:3.8-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
